version: "3.7"
services:
  chat-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
